### ISSUE TITLE
Support special non-numeric values NaN, Inf, -Inf

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-dump#4]
https://cloud.google.com/spanner/docs/data-types#floating_point_type
> When working with floating point numbers, there are special non-numeric values that need to be considered: NaN and +/-inf

`FLOAT64` columns can contain `NaN`, `Inf` and `-Inf` value but it is not correctly handled by `spanner-dump`.

```
$ spanner-cli
spanner> CREATE TABLE floats(pk INT64, col FLOAT64) PRIMARY KEY(pk);
Query OK, 0 rows affected (11.29 sec)

spanner> INSERT INTO floats(pk, col) VALUES(1, CAST("nan" AS FLOAT64)),(2, CAST("inf" AS FLOAT64)),(3, CAST("-inf" AS FLOAT64));
Query OK, 3 rows affected (0.04 sec)

spanner> SELECT * FROM floats;
+----+------+
| pk | col  |
+----+------+
| 1  | NaN  |
| 2  | +Inf |
| 3  | -Inf |
+----+------+
3 rows in set (31.4 msecs)
```
```
$ spanner-dump
...
INSERT INTO `floats` (`pk`, `col`) VALUES (1, NaN), (2, +Inf), (3, -Inf);
```

This line is not valid DML because `Nan` and `Inf` are not Cloud Spanner keywords.

It should be dumped the same value with `FORMAT('%T', f)`
https://cloud.google.com/spanner/docs/string_functions?hl=en#t_and_t_behavior

**Comment by apstndb** [comment]
Additionally, `fmt.Sprintf("%f", v.Float64)` doesn't preserve exact FLOAT64 value.

**Comment by yfuruyama** [comment]
Thank you for finding this.

> Additionally, fmt.Sprintf("%f", v.Float64) doesn't preserve exact FLOAT64 value.

Do you think [strconv.FormatFloat](https://golang.org/pkg/strconv/#FormatFloat) can work to preserve the exact value for float64, like `strconv.FormatFloat(v, 'g', -1, 64)`?
