### ISSUE TITLE
Is there a way to import to the emulator?

### ISSUE THREAD

**Issue by rakyll** [cloudspannerecosystem/spanner-dump#7]
I'd like to use the spanner-dump to migrate my schema and data from my production database to the emulator? I'd be great to be able to set the SPANNER_EMULATOR_HOST and be able to import to the emulator.

**Comment by yfuruyama** [comment]
Yes, you can.

spanner-dump already [supports](https://github.com/cloudspannerecosystem/spanner-dump/blob/master/dump.go#L70-L77) `SPANNER_EMULATOR_HOST` as an environment variable. So you can move data from Spanner service to emulator.

```
# export data from Spanner service
spanner-dump -p ${PROJECT} -i ${INSTANCE} -d ${DATABASE} > dump.sql

# import data to emulator
SPANNER_EMULATOR_HOST=localhost:9010 spanner-cli -p ${PROJECT} -i ${INSTANCE} -d ${DATABASE} < dump.sql
```

Note that second example uses spanner-**cli** for importing data.

**Comment by rakyll** [comment]
Great, thanks! Maybe it'd be great to mention it in the README.

**Comment by yfuruyama** [comment]
Will do! Thanks!
