### ISSUE TITLE
Convert dumper into a library

### ISSUE THREAD

**Issue by rakyll** [cloudspannerecosystem/spanner-dump#9]
I am working on a schema comparison tool for Spanner and I wonder if we can convert the dumper to a library, so I can utilize it rather than having to reimplement something similar myself.

**Comment by rakyll** [comment]
I just realized I can probably just copy the DumpDDLs method and modify according to my needs. Closing this issue for now.

**Comment by yfuruyama** [comment]
Sure, let me know if you will need a library for dumper.
